name: Generate and Deploy Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install sitemap_generator gem
        run: |
          gem install sitemap_generator --no-document

          # Export gem bin path into PATH
          echo "GEM_HOME=$(ruby -e 'puts Gem.dir')" >> $GITHUB_ENV
          echo "GEM_BIN_DIR=$(ruby -e 'puts Gem.bindir')" >> $GITHUB_ENV
          echo "$(ruby -e 'puts Gem.bindir')" >> $GITHUB_PATH

      - name: Generate Sitemap
        run: |
          echo "Running sitemap_generator from: $(which sitemap_generator)"
          sitemap_generator --url=https://kpopdev.github.io/ --out-path=./ --filename=sitemap.xml
          ls -l sitemap.xml

      - name: Commit and Push Sitemap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Generate and update sitemap.xml"
          file_pattern: "sitemap.xml"
