name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install sitemap_generator
        run: gem install sitemap_generator

      - name: Generate sitemap
        run: ruby Rakefile

      - name: Commit sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sitemap.xml.gz
          git commit -m "Generate sitemap" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
