name: Generate and Deploy Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for committing the sitemap
      pages: write # Needed if you also want to use it for deploying pages
      id-token: write # Needed for OIDC if using custom domains/advanced setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Ruby and add gem bin to PATH
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Use a specific Ruby version (e.g., matching ubuntu's default or a common one)
          # The 'setup-ruby' action automatically adds the gem executables to the PATH for subsequent steps.
          # No need for manual `echo "$(gem environment gemdir)/bin" >> $GITHUB_PATH`

      - name: Install sitemap_generator gem
        run: |
          gem install sitemap_generator
          
          # Optional: Debugging - print current PATH and check if sitemap_generator is findable
          echo "Current PATH: $PATH"
          which sitemap_generator || echo "sitemap_generator is still not found in PATH."

      - name: Generate Sitemap
        run: |
          # The sitemap_generator command should now be directly callable
          sitemap_generator --url=https://kpopdev.github.io/ --out-path=./ --filename=sitemap.xml
          # Ensure sitemap.xml is created in the root directory for deployment

      - name: Commit and Push Sitemap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Generate and update sitemap.xml"
          file_pattern: "sitemap.xml"
