name: Generate and Deploy Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for committing the sitemap
      pages: write # Needed if you also want to use it for deploying pages
      id-token: write # Needed for OIDC if using custom domains/advanced setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Use a specific Ruby version (e.g., matching ubuntu's default or a common one)
          # Removed bundler-cache as it requires a Gemfile, which we don't have

      - name: Generate Sitemap
        run: |
          # Install sitemap_generator gem
          gem install sitemap_generator

          # Locate the sitemap_generator executable path
          # This command finds where the gem executable is installed
          SITEMAP_GEN_PATH=$(gem environment gemdir)/gems/sitemap_generator-*/exe/sitemap_generator

          # Generate sitemap - Directly calling the executable using its full path
          "$SITEMAP_GEN_PATH" --url=https://kpopdev.github.io/ --out-path=./ --filename=sitemap.xml
          # Ensure sitemap.xml is created in the root directory for deployment

      - name: Commit and Push Sitemap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Generate and update sitemap.xml"
          file_pattern: "sitemap.xml"
