name: Generate and Deploy Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for committing the sitemap
      pages: write # Needed if you also want to use it for deploying pages
      id-token: write # Needed for OIDC if using custom domains/advanced setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Use a specific Ruby version (e.g., matching ubuntu's default or a common one)
          bundler-cache: true # Installs gems defined in Gemfile, or ensures Bundler is available

      - name: Generate Sitemap
        run: |
          # Install sitemap_generator gem if not already done by bundler-cache
          # (This step might be redundant if bundler-cache works, but acts as a fallback)
          gem install sitemap_generator

          # Generate sitemap - NOW using bundle exec
          # bundle exec ensures the command is found within the gem's context
          bundle exec sitemap_generator --url=https://kpopdev.github.io/ --out-path=./ --filename=sitemap.xml
          # Ensure sitemap.xml is created in the root directory for deployment

      - name: Commit and Push Sitemap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Generate and update sitemap.xml"
          file_pattern: "sitemap.xml"
