name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Gems
        run: gem install sitemap_generator

      - name: Generate Sitemap
        run: ruby Rakefile

      - name: Commit Sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sitemap.xml.gz
          git commit -m "Generate sitemap"
          git push
