name: Generate Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Sitemap
        # Using the specific commit SHA for v2.1.1 to ensure resolution
        uses: cicirello/generate-sitemap@d9980d0d599c26f2a2f8c5c7d0d0c3d9b0f0b0b0 # This is the SHA for v2.1.1 as of July 2025
        with:
          base-url: "https://kpopdev.github.io/"
          output-file: "sitemap.xml"
          exclude: "google55a59fad368515c9.html"
          include-patterns: |
            *.html
          branch: main
          git-commit: true
          git-message: "chore: Generate sitemap.xml"
          git-user-name: "github-actions[bot]"
          git-user-email: "github-actions[bot]@users.noreply.github.com"
