name: Generate and Deploy Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for committing the sitemap
      pages: write # Needed if you also want to use it for deploying pages
      id-token: write # Needed for OIDC if using custom domains/advanced setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Use a specific Ruby version

      - name: Install sitemap_generator gem and add to PATH
        run: |
          # Install sitemap_generator gem
          gem install sitemap_generator
          
          # Add the gem's executable directory to the PATH
          # This ensures that commands like 'sitemap_generator' are found
          echo "$(gem environment gemdir)/bin" >> $GITHUB_PATH
          # Also adding the specific Ruby version's bin directory just in case
          echo "/opt/hostedtoolcache/Ruby/3.2.8/x64/bin" >> $GITHUB_PATH # Hardcoding for 3.2.8 as seen in logs

      - name: Generate Sitemap
        run: |
          # Now, sitemap_generator command should be directly callable
          sitemap_generator --url=https://kpopdev.github.io/ --out-path=./ --filename=sitemap.xml
          # Ensure sitemap.xml is created in the root directory for deployment

      - name: Commit and Push Sitemap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Generate and update sitemap.xml"
          file_pattern: "sitemap.xml"
