name: Generate Sitemap

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install sitemap_generator
        run: gem install sitemap_generator

      - name: Generate sitemap
        # This step will create sitemap.xml.gz because compress is true in Rakefile
        run: ruby Rakefile

      - name: Commit sitemap
        # Now, we are telling git to add sitemap.xml.gz
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sitemap.xml.gz # <-- THIS LINE WAS CHANGED
          git commit -m "Generate sitemap" || echo "No changes, skipping commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
