name: Update DNS JSON

on:
  push:
    paths:
      - dns.txt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run script
        run: node scripts/update.js

      - name: Commit dns.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dns.json
          git commit -m "Auto update dns.json" || exit 0
          git push
